name: ascii_art
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  # cached_network_image: ^3.2.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.6
  google_sign_in: ^6.1.3
  provider: ^6.0.5
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  xterm: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/category.json
